### ISSUE TITLE
what is model for embedding

### ISSUE THREAD

**Issue by anti-machinee** [tae898/age-gender#11]
Thank you for your work. I have some question, please help me
1. Which model you are using for generating embedding?
2. Does gender classifier work well with any embedding extractor?

**Comment by tae898** [comment]
Hey,

1. ArcFace
2. Yeah probably, since any face embedding vectors will have some gender information included. But of course you'll have to train a new gender classifier if you want to use other embeddings than the ones I've used.

For more details, check out [the paper](https://arxiv.org/abs/2108.08186).
