### ISSUE TITLE
Hello can you please guideline if I want to run on colab?

### ISSUE THREAD

**Issue by tae898** [tae898/age-gender#2]
Hello can you please guideline if I want to run on colab?

_Originally posted by @maria-zafar in https://github.com/tae898/age-gender/issues/1#issuecomment-924928519_

**Comment by tae898** [comment]
@maria

**Comment by maria-zafar** [comment]
Okay addressing it here
What I am doing is I run app.py in one notebook using this command !python app.py and on another notebook in the same directory I execute  !python client.py --image-path $full_path and the I get is 

2021-09-22 13:00:37.517 DEBUG connectionpool - _new_conn: Starting new HTTP connection (1): 127.0.0.1:10002
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:


THIS IS NOT THE COMPLETE ERROR DISPLAY THOUGH!

**Comment by maria-zafar** [comment]
> Okay addressing it here
> What I am doing is I run app.py in one notebook using this command !python app.py and on another notebook in the same directory I execute !python client.py --image-path $full_path and the I get is
> 
> 2021-09-22 13:00:37.517 DEBUG connectionpool - _new_conn: Starting new HTTP connection (1): 127.0.0.1:10002
> Traceback (most recent call last):
> File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 170, in _new_conn
> (self._dns_host, self.port), self.timeout, **extra_kw
> File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 96, in create_connection
> raise err
> File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 86, in create_connection
> sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> THIS IS NOT THE COMPLETE ERROR DISPLAY THOUGH!

2021-09-22 13:00:33.749 INFO client - <module>: arguments given to client.py: {'url_face': 'http://127.0.0.1:10002/', 'url_age_gender': 'http://127.0.0.1:10003/', 'image_path': '/content/drive/MyDrive/age-gender/test_images/19.jpg'}
2021-09-22 13:00:33.750 DEBUG client - main: loading image ...
2021-09-22 13:00:33.751 INFO client - main: image loaded!
2021-09-22 13:00:33.751 DEBUG client - main: sending image to server...
2021-09-22 13:00:33.755 DEBUG connectionpool - _new_conn: Starting new HTTP connection (1): 127.0.0.1:10002
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fbcb7155750>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=10002): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcb7155750>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "client.py", line 104, in <module>
    main(**args)
  File "client.py", line 36, in main
    response = requests.post(url_face, json=data)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=10002): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbcb7155750>: Failed to establish a new connection: [Errno 111] Connection refused'))

THIS IS THE COMPLETE ERROR

**Comment by tae898** [comment]
@maria-zafar 

Check this out:
https://colab.research.google.com/github/tae898/age-gender/blob/main/age_gender-colab.ipynb

and lemme know if you face problems.

**Comment by maria-zafar** [comment]
> @maria-zafar
> 
> Check this out:
> https://colab.research.google.com/github/tae898/age-gender/blob/main/age_gender-colab.ipynb
> 
> and lemme know if you face problems.

okay responding back just right away because I am currently working on this.

**Comment by maria-zafar** [comment]
> @maria-zafar
> 
> Check this out:
> https://colab.research.google.com/github/tae898/age-gender/blob/main/age_gender-colab.ipynb
> 
> and lemme know if you face problems.

Yes the code works fine. Thank you! You are a great help!
Can you please also highlight where in code I get the predicted values so that I can return those numbers?

**Comment by tae898** [comment]
> > @maria-zafar
> > Check this out:
> > https://colab.research.google.com/github/tae898/age-gender/blob/main/age_gender-colab.ipynb
> > and lemme know if you face problems.
> 
> Yes the code works fine. Thank you! You are a great help!
> Can you please also highlight where in code I get the predicted values so that I can return those numbers?

Take a look at the last cell of the notebook:
```python
import pickle

for pickle_path in glob('./test-images/*.pkl'):
    with open(pickle_path, 'rb') as stream:
        results = pickle.load(stream)
        print(pickle_path, [(key, len(val)) for key, val in results.items()])
```

`results` is a dict, whose keys are `bboxes`, `det_scores`, `landmarks`, `embeddings`, `genders`, and `ages`. All of their values have the same length, which is the number of the faces detected.  

For example, if we take a look at `./test-images/stock-photo-happy-black-famliy-enjoy-friendship-and-love-together-mother-and-son-playing-and-having-fun-at-the-1931388422.jpg.pkl`, and their `genders` and `ages`:

```python
In [5]: results['genders']
Out[5]: [{'m': 0.0, 'f': 1.0, 'entropy': 0.0}, {'m': 0.0, 'f': 1.0, 'entropy': 0.0}]

In [6]: results['ages']
Out[6]: 
[{'mean': 32.501953125, 'entropy': 1.3051009520110988},
 {'mean': 10.103515625, 'entropy': 1.4263272984354396}]
```

Is everything clear now?

**Comment by maria-zafar** [comment]
> > > @maria-zafar
> > > Check this out:
> > > https://colab.research.google.com/github/tae898/age-gender/blob/main/age_gender-colab.ipynb
> > > and lemme know if you face problems.
> > 
> > 
> > Yes the code works fine. Thank you! You are a great help!
> > Can you please also highlight where in code I get the predicted values so that I can return those numbers?
> 
> Take a look at the last cell of the notebook:
> 
> ```python
> import pickle
> 
> for pickle_path in glob('./test-images/*.pkl'):
>     with open(pickle_path, 'rb') as stream:
>         results = pickle.load(stream)
>         print(pickle_path, [(key, len(val)) for key, val in results.items()])
> ```
> 
> `results` is a dict, whose keys are `bboxes`, `det_scores`, `landmarks`, `embeddings`, `genders`, and `ages`. All of their values have the same length, which is the number of the faces detected.
> 
> For example, if we take a look at `./test-images/stock-photo-happy-black-famliy-enjoy-friendship-and-love-together-mother-and-son-playing-and-having-fun-at-the-1931388422.jpg.pkl`, and their `genders` and `ages`:
> 
> ```python
> In [5]: results['genders']
> Out[5]: [{'m': 0.0, 'f': 1.0, 'entropy': 0.0}, {'m': 0.0, 'f': 1.0, 'entropy': 0.0}]
> 
> In [6]: results['ages']
> Out[6]: 
> [{'mean': 32.501953125, 'entropy': 1.3051009520110988},
>  {'mean': 10.103515625, 'entropy': 1.4263272984354396}]
> ```
> 
> Is everything clear now?

Yes but why do we have 2 lists in results['ages'] is it for male and female? Also just to assure if I want to calculate mse or mae instead of entropy and if I do by changing loss to "mse" instead of "cse" in age.json in models since model folder has loss.py file having a function mse would that work?

**Comment by tae898** [comment]
> > > > @maria-zafar
> > > > Check this out:
> > > > https://colab.research.google.com/github/tae898/age-gender/blob/main/age_gender-colab.ipynb
> > > > and lemme know if you face problems.
> > > 
> > > 
> > > Yes the code works fine. Thank you! You are a great help!
> > > Can you please also highlight where in code I get the predicted values so that I can return those numbers?
> > 
> > 
> > Take a look at the last cell of the notebook:
> > ```python
> > import pickle
> > 
> > for pickle_path in glob('./test-images/*.pkl'):
> >     with open(pickle_path, 'rb') as stream:
> >         results = pickle.load(stream)
> >         print(pickle_path, [(key, len(val)) for key, val in results.items()])
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `results` is a dict, whose keys are `bboxes`, `det_scores`, `landmarks`, `embeddings`, `genders`, and `ages`. All of their values have the same length, which is the number of the faces detected.
> > For example, if we take a look at `./test-images/stock-photo-happy-black-famliy-enjoy-friendship-and-love-together-mother-and-son-playing-and-having-fun-at-the-1931388422.jpg.pkl`, and their `genders` and `ages`:
> > ```python
> > In [5]: results['genders']
> > Out[5]: [{'m': 0.0, 'f': 1.0, 'entropy': 0.0}, {'m': 0.0, 'f': 1.0, 'entropy': 0.0}]
> > 
> > In [6]: results['ages']
> > Out[6]: 
> > [{'mean': 32.501953125, 'entropy': 1.3051009520110988},
> >  {'mean': 10.103515625, 'entropy': 1.4263272984354396}]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is everything clear now?
> 
> Yes but why do we have 2 lists in results['ages'] is it for male and female? Also just to assure if I want to calculate mse or mae instead of entropy and if I do by changing loss to "mse" instead of "cse" in age.json in models since model folder has loss.py file having a function mse would that work?

It's not 2 lists in `results['ages']`, but a list of two dicts. There are two dicts since there are two faces in this image.

mse loss should work:
https://github.com/tae898/age-gender/blob/main/model/loss.py

But cse gave me the best results.

**Comment by maria-zafar** [comment]
> > > > > @maria-zafar
> > > > > Check this out:
> > > > > https://colab.research.google.com/github/tae898/age-gender/blob/main/age_gender-colab.ipynb
> > > > > and lemme know if you face problems.
> > > > 
> > > > 
> > > > Yes the code works fine. Thank you! You are a great help!
> > > > Can you please also highlight where in code I get the predicted values so that I can return those numbers?
> > > 
> > > 
> > > Take a look at the last cell of the notebook:
> > > ```python
> > > import pickle
> > > 
> > > for pickle_path in glob('./test-images/*.pkl'):
> > >     with open(pickle_path, 'rb') as stream:
> > >         results = pickle.load(stream)
> > >         print(pickle_path, [(key, len(val)) for key, val in results.items()])
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > `results` is a dict, whose keys are `bboxes`, `det_scores`, `landmarks`, `embeddings`, `genders`, and `ages`. All of their values have the same length, which is the number of the faces detected.
> > > For example, if we take a look at `./test-images/stock-photo-happy-black-famliy-enjoy-friendship-and-love-together-mother-and-son-playing-and-having-fun-at-the-1931388422.jpg.pkl`, and their `genders` and `ages`:
> > > ```python
> > > In [5]: results['genders']
> > > Out[5]: [{'m': 0.0, 'f': 1.0, 'entropy': 0.0}, {'m': 0.0, 'f': 1.0, 'entropy': 0.0}]
> > > 
> > > In [6]: results['ages']
> > > Out[6]: 
> > > [{'mean': 32.501953125, 'entropy': 1.3051009520110988},
> > >  {'mean': 10.103515625, 'entropy': 1.4263272984354396}]
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Is everything clear now?
> > 
> > 
> > Yes but why do we have 2 lists in results['ages'] is it for male and female? Also just to assure if I want to calculate mse or mae instead of entropy and if I do by changing loss to "mse" instead of "cse" in age.json in models since model folder has loss.py file having a function mse would that work?
> 
> It's not 2 lists in `results['ages']`, but a list of two dicts. There are two dicts since there are two faces in this image.
> 
> mse loss should work:
> https://github.com/tae898/age-gender/blob/main/model/loss.py
> 
> But cse gave me the best results.

isn't result['ages'] an aggregated result of all images in a loop?
