### ISSUE TITLE
FPS Drop

### ISSUE THREAD

**Issue by pbarrero** [tae898/age-gender#6]
Hello,
I'm running your docker on a GPU environment and after the face recognition I'm on around 30 FPS. But after connecting with the age_gender for predictions, drop to 12 FPS with the CPU over 400%. Is there a way to improve this performance or to use the GPU?

Thanks!

**Comment by tae898** [comment]
Hi,

Thanks for trying out my docker images.
The `Dockerfile` of the `age-gender` docker image currently looks like this:

```dockerfile
FROM python:3.7.10
ENV DEBIAN_FRONTEND=noninteractive 

WORKDIR /app
COPY . .

RUN apt update
RUN python3.7 -m pip install --upgrade pip
RUN python3.7 -m pip install -r requirements.txt

CMD ["python3.7", "app.py"]
```

As you can see, this image is not based on an NVIDIA pytorch cuda image. I didn't do this because (i) the image will become too large for such a small application, and (ii) I thought that the age-gender MLP is too small to benefit from GPU computation.

Unfortunately, the GPU in my machine is broken at this moment, but I'd still like to try running age-gender model on a GPU.

If you have time, you can perhaps modify line `FROM python:3.7.10` to `FROM nvcr.io/nvidia/pytorch:21.10-py3` in the `Dockerfile`, build the image, run it with cuda, and test the FPS.

If not, I can perhaps try this in the cloud some other day.

**Comment by pbarrero** [comment]
Hello,
Thanks for your response!

I have tried your suggestion and it seems to make the docker work with GPU, also had to change the torch version on the requirements for this one `torch==1.10.0a0+0aef44c` 

Now I'm getting this runtime error when predicting an age gender on an image:

`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_addmm)`

After seeing this error I have trained both, age and gender models, with GPU but I'm still  getting the same error.

 At this point I have no other clues. Any ideas?

Thanks so much!

**Comment by tae898** [comment]
Hi,

Thanks for pointing out the issue. I forgot to move the torch tensor to a GPU when it's running on a GPU.
It's fixed and I pushed the docker image.

Now you can run the cuda-enabled `age-gender` image by running:

```sh
docker run -it --rm -p 10003:10003 --gpus all tae898/age-gender-cuda
``` 

Can you also report the FPS? Also, can you tell me the specs of your machine (e.g., CPU and GPU) ?

Thanks!

**Comment by tae898** [comment]
Hey there,

I actually measure the fps myself with webcam:

face-detection-recognition: gpu
age-gender: gpu
![face-gpu-agegender-gpu](https://user-images.githubusercontent.com/10544311/153349160-948ee52a-f0df-4c10-b266-c13339faee29.png)

face-detection-recognition: gpu
age-gender: cpu
![face-gpu-agegender-cpu](https://user-images.githubusercontent.com/10544311/153349195-51a8f51a-e5b8-4329-b32a-c21575fbd40d.png)

face-detection-recognition: cpu
age-gender: gpu
![face-cpu-agegender-gpu](https://user-images.githubusercontent.com/10544311/153349211-033a8176-9f12-43ff-8970-ec01df00c1aa.png)

face-detection-recognition: cpu
age-gender: cpu
![face-cpu-agegender-cpu](https://user-images.githubusercontent.com/10544311/153349233-3e21c366-6552-454e-accb-a71e2ded6b32.png)

So on my machine (i7-10875H CPU and RTX 2060 Max-Q GPU) fps is around 10 when the face-detection-recognition is running on a GPU, and it is around 2 when it's running on a CPU. It doesn't matter if age-gender is running on a CPU or a GPU, which means that the bottleneck is the face-detection-recognition. I'll wrap up the code soon and push the code.

There are so many factors that can affect the fps:
1. Logging, console print.
1. Networking.
1. Using 16bit floating point, instead of 32. 
1. Better GPU and CPU
1. etc.
1. Number of faces detected in an image.

I'd still be curious to see your fps!
